config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'mains#index'
  devise_for :users
  devise_scope :user do
    get "admin" => "devise/sessions#new"
  end

  #root to: "home#index"
  get "what" => "mains#what"
  resources :news 
  resources :schedules do
    collection do
      get "reserve" => "schedules#reserve"
    end
  end
  resources :discographies
  resources :items
  resources :contacts do
    collection do
      post "ticket_conf" => "contacts#ticket_conf"
      post "ticket_thanks" => "contacts#ticket_thanks"
      get "main_contact" => "contacts#main_contact"
      post "conf" => "contacts#conf"
      post "thanks" => "contacts#thanks"
      get "item_contact" => "contacts#item_contact"
      post "item_conf" => "contacts#item_conf"
      post "item_thanks" => "contacts#item_thanks"
    end
  end
  resources :clans
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clan.rb
class Clan < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  #validates :name, :email, :date, :count, presence: true
end

app/models/discography.rb
class Discography < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/main.rb
class Main < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/clans_controller.rb
class ClansController < ApplicationController
  def index
    @clan_gu = Clan.all.where(part: 1)
    @clan_ba = Clan.all.where(part: 2)
    @clan_dr = Clan.all.where(part: 3)
    @clan_ot = Clan.all.where(part: 4)
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/contacts_controller.rb
require "date"
class ContactsController < ApplicationController

  def index
    @t_contact = Contact.new
    @schedule = Schedule.all.where(reservation: 0).where("DATE(date) >= '#{Date.today}'")
    @name = session[:name]
    @email = session[:email]
    @date = session[:date]
    @count = session[:count]
  end

  def ticket_conf
    @t_contact = Contact.new
    @schedule = Schedule.all.where(reservation: 0)
    unless params[:contact][:date]
      flash[:notice] = "日程が選択されておりません"
      render :index
    else
      @name = params[:contact][:name]
      @email = params[:contact][:email]
      @date = params[:contact][:date]
      @place = Schedule.find_by(date: @date)
      @count = params[:contact][:count]
      session[:name] = @name
      session[:email] = @email
      session[:date] = @date
      session[:count] = @count
    end
  end

  def ticket_thanks 
    @t_contact = Contact.new(contact_params) 
    if @t_contact.save
      session[:name] = nil
      session[:email] = nil
      session[:date] = nil
      session[:count] = nil
      ContactMailer.contact_mail(@t_contact).deliver_later
    else
      render :index
    end
  end

  def main_contact
    @contact = Contact.new
    @name = session[:name]
    @email = session[:email]
    @details = session[:details]
  end

  def conf
    @contact = Contact.new
    @name = params[:contact][:name]
    @email = params[:contact][:email]
    @details = params[:contact][:details]
    session[:name] = @name
    session[:email] = @email
    session[:details] = @details
  end

  def thanks
    @contact = Contact.new(main_contact_params) 
    if session[:name]
      if @contact.save
        session[:name] = nil
        session[:email] = nil
        session[:details] = nil
        ContactMailer.main_contact_mail(@contact).deliver_later
      else
        render :index
      end  
    else
      redirect_to("/.index")
    end
  end

  def item_contact
    @contact = Contact.new
    @name = session[:name]
    @email = session[:email]
    @details = session[:details]
  end

  def item_conf
    @contact = Contact.new
    @name = params[:contact][:name]
    @email = params[:contact][:email]
    @details = params[:contact][:details]
    session[:name] = @name
    session[:email] = @email
    session[:details ] = @details
  end

  def item_thanks
    @contact = Contact.new(main_contact_params)
    if @contact.save
        session[:name] = nil
        session[:email] = nil
        session[:details] = nil
        ContactMailer.item_contact_mail(@contact).deliver_later
      else
        render :index
      end  
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :date, :count)
  end

  def main_contact_params
    params.require(:contact).permit(:name, :email, :details)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @item_cd = Discography.where(types: 1..2).order("id ASC")
    @item_dvd = Discography.where(types: 3) 
    @good = Item.all
  end

  def show
  end

  def new
  end

  def edit
  end

end

app/controllers/mains_controller.rb
require 'date'
class MainsController < ApplicationController
  def index
    @news = News.all.order("id DESC").first
    @lives = Schedule.all.where(types: "0").where("DATE(date) >= '#{Date.today}'").order("date ASC").first
  end

  def what
    @what = Main.all.first
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  before_action :news_set, only: [:show]

  def index
    @news = News.all.order("id DESC")
  end

  def show
  end

  def new
  end

  def edit
  end

  protected
  def news_set
    @news = News.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clans_helper.rb
module ClansHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
  #テキストの中にurlがあるとリンクを付ける
  def text_url_link_set text
    URI.extract(text, ['http']).uniq.each do |url|
      sub_text = ""
      sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"
      text.gsub!(url, sub_text)
    end
    text 
  end
end

app/views/contacts/_form.html.erb
 <%= form_for @t_contact, :url => ticket_conf_contacts_path, method: :post do |t| %>
    <% if @schedule.present? %>
      <dl class="contact_form">
        <dt><%= t.label :name, "お名前"%></dt>
        <dd><%= t.text_field :name, :value => @name %></dd>
        <dt><%= t.label :email, "メールアドレス" %></dt>
        <dd><%= t.email_field :email, :value => @email %></dd>
        <dt>日程</dt>
        <dd>
        <% @schedule.each do |i| %>
          <% if @date.present? %>
            <% if @date.to_date == i.date %>
              <%= t.radio_button :date, i.date, {:checked => true} %>
            <% else %>
              <%= t.radio_button :date, i.date, {} %>
            <% end %>
          <% else %>
            <%= t.radio_button :date, i.date, {} %>
          <% end %>
          <%= t.label :date, i.date.strftime("%y年%m月%d日") + " " + i.place, value: i.date %><br>
        <% end %>
        </dd>
        <dt><%= t.label :count, "枚数" %></dt>
        <dd><%= t.number_field :count, :value => @count %></dd>
      </dl>
      <p class="center"><%= t.submit "確認画面", :class => "validate" %></p>
    <% else %>
      現在予約出来る日程はありません
    <% end %>

<% end %>

app/views/contacts/conf.html.erb
<h2>お問い合わせ確認</h2>
<div class="contact_content">
  <%= form_for @contact, :url => thanks_contacts_path do |i| %>
    <dl class="contact_form">
      <dt>お名前</dt>
      <dd>
      <%= i.hidden_field :name, :value => @name %>
      <%= @name %>
      </dd>
      <dt>メールアドレス</dt>
      <dd>
      <%= i.hidden_field :email, :value => @email %>
      <%= @email %>
      </dd>
      <dt>お問い合わせ内容</dt>
      <dd>
      <%= i.hidden_field :details, :value => @details %>
      <%= simple_format(@details) %>
      </dd>
      <div class="center">
        <p>こちらの内容で間違いありませんか？</p>
        <%= link_to("戻る", :back) %>
        <%= i.submit "送信" %>
      </div>
    <% end %>
</div> 

app/views/contacts/index.html.erb
<h2>チケット予約</h2>
<section class="contact_content tab_contents tab_content_default">
  <%= render "form" %> 
</section>

app/views/contacts/item_conf.html.erb
<h2>ご購入に関するお問い合わせ確認</h2>
<div class="contact_content">
  <%= form_for @contact, :url => item_thanks_contacts_path do |i| %>
    <dl class="contact_form">
      <dt>お名前</dt>
      <dd>
      <%= i.hidden_field :name, :value => @name %>
      <%= @name %>
      </dd>
      <dt>メールアドレス</dt>
      <dd>
      <%= i.hidden_field :email, :value => @email %>
      <%= @email %>
      </dd>
      <dt>お問い合わせ内容</dt>
      <dd>
      <%= i.hidden_field :details, :value => @details %>
      <%= simple_format(@details) %>
      </dd>
      <div class="center">
        <p>こちらの内容で間違いありませんか？</p>
        <%= link_to("戻る", :back) %>
        <%= i.submit "送信" %>
      </div>
    <% end %>
</div>

app/views/contacts/item_contact.html.erb
<section class="contact_content tab_contents tab_content_default">
<h2>ご購入に関するお問い合わせ</h2>
 <%= form_for @contact, :url => item_conf_contacts_path, method: :post do |t| %>
    <dl class="contact_form">
      <dt><%= t.label :name, "お名前"%></dt>
      <dd><%= t.text_field :name, :value => @name %></dd>
      <dt><%= t.label :email, "メールアドレス" %></dt>
      <dd><%= t.email_field :email, :value => @email %></dd>
      <dt><%= t.label :details, "お問い合わせ内容" %></dt>
      <dd><%= t.text_area :details, :size => "50x10", :value => @details, :placeholder => "goodsの◯◯が欲しいです。等" %></dd>
    </dl>
    <p class="center"><%= t.submit "確認画面", :class => "contact_validates" %></p>
  <% end %>
</section>

app/views/contacts/item_thanks.html.erb
<h2>ご購入に関するお問い合わせ完了</h2>
<p>
  ご購入に関するお問い合わせを承ったぞ！
  <br />
  3日以内に我輩から確認のメールを送らせて頂くいのでしばしお待ちをψ(｀∇川)ψ
  <br />
  万が一送られてこない場合はお手数だが
  <a href="mailto:from_vampire_rose@yahoo.co.jp">from_vampire_rose@yahoo.co.jp</a>
  <br />
  までクレームのメールをくだされ・゜・(ノД`)・゜・
</p>

app/views/contacts/main_contact.html.erb
<h2>お問い合わせ</h2>
<section class="contact_content tab_contents tab_content_default">
  <%= form_for @contact, :url => conf_contacts_path, method: :post do |t| %>
    <dl class="contact_form">
      <dt><%= t.label :name, "お名前"%></dt>
      <dd><%= t.text_field :name, :value => @name %></dd>
      <dt><%= t.label :email, "メールアドレス" %></dt>
      <dd><%= t.email_field :email, :value => @email %></dd>
      <dt><%= t.label :details, "お問い合わせ内容" %></dt>
      <dd><%= t.text_area :details, :size => "50x10", :value => @details %></dd>
    </dl>
    <p class="center"><%= t.submit "確認画面", :class => "contact_validates" %></p>
  <% end %>
</section>

app/views/contacts/thanks.html.erb
<h2>チケット予約完了</h2>
<p>
  予約を承ったぞ！
  <br />
  3日以内に我輩から確認のメールを送らせて頂くいのでしばしお待ちをψ(｀∇川)ψ
  <br />
  万が一送られてこない場合はお手数だが
  <a href="mailto:from_vampire_rose@yahoo.co.jp">from_vampire_rose@yahoo.co.jp</a>
  <br />
  までクレームのメールをくだされ・゜・(ノД`)・゜・
</p>

app/views/contacts/ticket_conf.html.erb
<h2>チケット予約確認</h2>
<div class="contact_content">
  <%= form_for @t_contact, :url => ticket_thanks_contacts_path do |i| %>
    <dl class="contact_form">
      <dt>お名前</dt>
      <dd>
      <%= i.hidden_field :name, :value => @name %>
      <%= @name %>
      </dd>
      <dt>メールアドレス</dt>
      <dd>
      <%= i.hidden_field :email, :value => @email %>
      <%= @email %>
      </dd>
      <dt>日程</dt>
      <dd>
      <%= i.hidden_field :date, :value => @date %>
      <%= @date.to_date.strftime("%y年%m月%d日") %> <%= @place.place %>
      </dd>
      <dt>枚数</dt>
      <dd>
      <%= i.hidden_field :count, :value => @count %>
      <%= @count %>枚
      </dd>
    </dl>
    <div class="center">
      <p>こちらの内容で間違いありませんか？</p>
      <%= link_to("戻る", :action => :index) %>
      <%= i.submit "送信" %>
    </div>
  <% end %>
</div>

app/views/contacts/ticket_thanks.html.erb
<h2>チケット予約完了</h2>
<p>
  予約を承ったぞ！
  <br />
  3日以内に我輩から確認のメールを送らせて頂くいのでしばしお待ちをψ(｀∇川)ψ
  <br />
  万が一送られてこない場合はお手数だが
  <a href="mailto:from_vampire_rose@yahoo.co.jp">from_vampire_rose@yahoo.co.jp</a>
  <br />
  までクレームのメールをくだされ・゜・(ノД`)・゜・
</p>